import {PixelRatio, StyleSheet} from 'react-native';

const fontScale = PixelRatio.getFontScale();
export const getFontSize = (size: any) => size / fontScale;

export const FontStyle = StyleSheet.create({
  fontMedium14: {
    fontFamily: 'Avenir Medium',
    fontSize: 14,
    color: '#242734',
    // fontWeight: '500',
    lineHeight: 21,
  },
  fontMedium14LightGray: {
    fontFamily: 'Avenir Medium',
    fontSize: 14,
    color: '#7e7e7e',
    // fontWeight: '500',
    lineHeight: 21,
  },
  fontMediumGray13: {
    fontFamily: 'Avenir Medium',
    fontSize: 13,
    color: '#141414',
    lineHeight: 19.5,
  },
  fontMedium10: {
    fontFamily: 'Avenir Medium',
    fontSize: 10,
    color: 'rgba(36, 39, 52, 0.6)',
    lineHeight: 15.5,
  },
  fontHeavy13White: {
    fontFamily: 'Avenir Heavy',
    fontSize: 13,
    color: '#ffff',
    // fontWeight: '800',
    lineHeight: 19.5,
  },
  fontHeavy12: {
    fontFamily: 'Avenir Heavy',
    fontSize: 12,
    color: '#242734',
    // fontWeight: '800',
    lineHeight: 18,
  },
  fontMedium12: {
    fontFamily: 'Avenir Medium',
    fontSize: 12,
    // fontWeight: '500',
    color: '#242734',
    lineHeight: 18,
  },
  fontMedium12Gray: {
    fontFamily: 'Avenir Medium',
    fontSize: 12,
    // fontWeight: '500',
    color: '#7E7E7E',
    lineHeight: 18,
  },
  fontHeavy15White: {
    fontFamily: 'Avenir Heavy',
    fontSize: 15,
    color: '#ffff',
    // fontWeight: '500',
    lineHeight: 22.5,
  },
  fontBlack15: {
    fontFamily: 'Avenir Black',
    fontSize: 15,
    color: '#242734',
    // fontWeight: '500',
    lineHeight: 22.5,
  },
  fontBlack14: {
    fontFamily: 'Avenir Black',
    fontSize: 14,
    color: '#242734',
    // fontWeight: '700',
    lineHeight: 21,
  },
  fontHeavy14: {
    fontFamily: 'Avenir Heavy',
    fontSize: 14,
    color: '#242734',
    // fontWeight: '800',
    lineHeight: 21,
  },
  fontHeavy15: {
    fontFamily: 'Avenir Heavy',
    fontSize: 15,
    color: '#242734',
    // fontWeight: '800',
    lineHeight: 24,
  },
  fontHeavy16: {
    fontFamily: 'Avenir Heavy',
    fontSize: 16,
    color: '#242734',
    // fontWeight: '800',
    lineHeight: 24,
  },
  fontMedium15: {
    fontFamily: 'Avenir Medium',
    fontSize: 15,
    color: '#242734',
    // fontWeight: '500',
    lineHeight: 22.5,
  },
  fontMedium16: {
    fontFamily: 'Avenir Medium',
    fontSize: 16,
    // fontWeight: '500',
    color: '#242734',
    lineHeight: 24,
  },
  fontHeavy18: {
    fontFamily: 'Avenir Heavy',
    fontSize: 18,
    // fontWeight: '800',
    color: '#242734',

    lineHeight: 27,
  },

  fontMedium17: {
    fontFamily: 'Avenir Medium',
    fontSize: 17,
    // fontWeight: '500',
    color: '#242734',
    lineHeight: 25.5,
  },

  fontMedium18: {
    fontFamily: 'Avenir Medium',
    fontSize: 18,
    // fontWeight: '500',
    color: '#242734',
    lineHeight: 27,
  },
  fontHeavy20: {
    fontFamily: 'Avenir Heavy',
    fontSize: 20,
    // fontWeight: '800',
    color: '#242734',
    lineHeight: 30,
  },
  fontMedium22: {
    fontFamily: 'Avenir Medium',
    fontSize: 22,
    // fontWeight: '500',
    color: '#242734',
    lineHeight: 33,
  },
  fontHeavy22: {
    fontFamily: 'Avenir Heavy',
    fontSize: 22,
    // fontWeight: '800',
    color: '#242734',
    lineHeight: 33,
  },
  fontMedium24: {
    fontFamily: 'Avenir Medium',
    fontSize: 24,
    // fontWeight: '500',
    color: '#242734',
    lineHeight: 36,
  },
  fontHeavy24: {
    fontFamily: 'Avenir Heavy',
    fontSize: 24,
    // fontWeight: '800',
    color: '#242734',
    lineHeight: 36,
  },
  fontMedium31: {
    fontFamily: 'Avenir Medium',
    fontSize: 31,
    // fontWeight: '500',
    color: '#242734',
  },
  fontHeavy40: {
    fontFamily: 'Avenir Heavy',
    fontSize: 40,
    // fontWeight: '800',
    color: '#242734',
  },
  fontRegular14: {
    fontSize: 14,
    fontFamily: 'Avenir Regular',
    lineHeight: 21,
    color: '#242734',
  },
  fontRegular16: {
    fontSize: 16,
    fontFamily: 'Avenir Regular',
    lineHeight: 24,
    color: '#242734',
  },
  fontRegular12: {
    fontSize: 12,
    fontFamily: 'Avenir Regular',
    lineHeight: 18,
    color: '#242734',
  },
});
